### ISSUE TITLE
[Bug] Generated Junit Report with failure is missing the <failure/> tag inside the report

### ISSUE THREAD

**Issue by FilipeGoncalvesBasecone** [MicroFocus/lrc-gh-action#5]
The action now correctly generates the Junit report along with PDF, etc but when the test fails the XML report is missing the inner tag for <failure></failure>.

An example of this is one of our latest runs:
![image](https://github.com/MicroFocus/lrc-gh-action/assets/131873731/24a44487-6302-4802-96d4-bd8194ff5dfd)

Afterwards we upload the report with XRay to Jira but the test is marked as PASSED instead of FAILED.
On Azure Pipelines when the test is failed this tag exists inside the testcase

```
<testcase classname="com.microfocus.srl.Test" name="TestName" status="FAILED" time="1968.51">   
      <failure message="Test run status is FAILED" type="FAILED"/> 
</testcase>
```

Could you take a look into this?
We can send more evidence if needed from our runs

**Comment by weisun10** [comment]
@FilipeGoncalvesBasecone thanks for reporting it! 
The action was updated to include the "failure" element when test run status != PASSED.

**Comment by FilipeGoncalvesBasecone** [comment]
@weisun10 no problem happy to help! 😄 
Will close this issue then and thanks so much for the feedback
